### ISSUE TITLE
Create dropdown menus for levels and date

### ISSUE THREAD

**Issue by asakura42** [t-lou/MiKan#1]
I think it will be nice to choose levels and date from list and without typing every time

**Comment by t-lou** [comment]
good point, will do tomorrow (if vaccination doesn't defeat me)

do you have suggestion how to apply dropdown for date? don't want to import any third party lib

**Comment by t-lou** [comment]
> I think it will be nice to choose levels and date from list and without typing every time

How is it now?

**Comment by asakura42** [comment]
Noice!
